"""device registry

`sync_logs.device_id` is free text pointing at no table, so the server cannot
say which units run an old model, which have not synced in days, or which to
roll back when a release goes wrong. This table is where those answers come
from.

`tenant_id` is non-nullable by design. Pak Wahyono's rule is that one hospital
may run several devices but one device never serves two, and a rule the
database enforces cannot be forgotten by a future endpoint.

MAC and credential are separate columns because a MAC is visible to anyone on
the same network and can be changed from the operating system. It identifies a
device; it does not authenticate one. Only the credential's hash is stored,
the same way user passwords are.

`sync_logs.device_id` is deliberately left alone here. Turning it into a
foreign key means migrating the rows already in it, and that deserves its own
revision rather than riding along with the table creation.

Revision ID: 0420c9949e62
Revises: a1f4c7d92b30
Create Date: 2026-09-08 13:58:21.454130

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = '0420c9949e62'
down_revision: Union[str, None] = 'a1f4c7d92b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('credential_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
